services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - TZ=Etc/UTC
      - PASSWORD=changelater
      - SUDO_PASSWORD=changelater
    volumes:
      - ide_codeoss:/config
    ports:
      - 8443:8443
    restart: unless-stopped
    networks:
     - ovpn_net
networks:
 ovpn_net:
  external: true

volumes:
 ide_codeoss:
  external: true