services:
 portainer:
  image: portainer/portainer-ce:lts
  ports:
   - 8000:8000
   - 9443:9443
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
   - portainer_data:/data
  networks:
   - ovpn_net
  cap_add:
   - NET_ADMIN
  restart: unless-stopped

volumes:
 portainer_data:
  external: true
networks:
 ovpn_net:
  external: true